### ISSUE TITLE
https://bfarm-referenzdatenbank-explorer-frontend.onrender.com keine Eingaben möglich?

### ISSUE THREAD

**Issue by bneidhold** [SvenSommer/bfarm_Referenzdatenbank_explorer#2]
bitte Beispiele geben, was man auf der Seite https://bfarm-referenzdatenbank-explorer-frontend.onrender.com eingeben kann. Ich schaffe es nicht, der GUI irgendwelche Daten zu entlocken.

**Comment by SvenSommer** [comment]
Hallo @bneidhold,

ich habe für dieses Projekt eine Visualisierung der vom BfArM bereitgestellten Referenzdatenbank erstellt. Da nur wenig Interesse an dem Projekt bestand und es für mich mit (privaten) Serverkosten verbunden war, habe ich von einer kostenpflichtigen Always-On-Server-Option zu einer bedarfsorientierten Lösung gewechselt, die leider nicht gut funktioniert, da das Backend sehr lange zum hochfahren braucht.

Ich habe die Anwendung nun neu deployed, sodass du die Visualisierung [hier](https://bfarm-referenzdatenbank-explorer-frontend.onrender.com/) einsehen kannst. 

Hier ist meine Zusammenfassung zu den vom BfArM bereitgestellten Daten:

* Die Verknüpfbarkeit der Daten ist nicht gegeben, da es keine Mappingtabelle zwischen der PZN und der BfArM-Zulassungsnummer gibt.
* Die Datenqualität ist eher schlecht, da es inhaltlich keine klare Trennung zwischen Wirkstoffstärken (Zahl) und Wirkstoffstärken (Einheit) gibt und teilweise auch keine Aufsplitterung innerhalb der einzelnen Wirkstoffe vorhanden ist. Eine Auswertung dazu findest du hier:
https://github.com/SvenSommer/bfarm_Referenzdatenbank_explorer/blob/main/test/pzn_errors.xml

Falls du die Visualisierung nicht mehr benötigst, würde ich wieder in den "Kostensparmodus" wechseln.

**Comment by bneidhold** [comment]
Hi Robert,
ich habe es mir angesehen und ja ich brauche es nicht mehr. Ich bin darauf gestoßen, weil der Link zum Projekt auf den offiziellen E-Rezept Seiten aufgetaucht ist. Da sollte der Link entfernt werden - weil es so aussieht, als ob das ein offizielles Spezifikationsartefakt ist ;-)

**Comment by SvenSommer** [comment]
Ja, guter Punkt. Das nehmen wir wieder raus.

**Comment by SvenSommer** [comment]
https://github.com/gematik/api-erp/pull/208
